import { useRouter } from "next/router";
import { type NextPage } from "next";
import Link from "next/link";

import { api } from "~/utils/api";
import Head from "next/head";

const NewNote: NextPage = () => {
  const router = useRouter()
  const noteId = router.query.id as string
  const { data, isLoading } = api.notes.detailNote.useQuery({ id: noteId })

  if (isLoading) return <>Loading...</>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <Link href={'/'}>Go Back</Link>
          <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20">
            <h3 className="text-2xl font-bold">{data?.title}</h3>
            <div className="text-lg">
              {data?.description}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default NewNote;
